### ISSUE TITLE
Crash with updated libco

### ISSUE THREAD

**Issue by fr500** [fr500/dosbox-svn#3]
![image](https://user-images.githubusercontent.com/1721040/48888033-631ba680-edff-11e8-94e3-fa5747d8397d.png)

This change broke dosbox on 32 bit ARM android
@webgeek1234 do you know how can I undef __thumb2__

**Comment by webgeek1234** [comment]
I'm missing how this compiles at all... But in a jni setting, you set
LOCAL_ARM_MODE := arm
By default, stuff seems to compile in thumb mode for size, even though arm mode is technically native.

**Comment by fr500** [comment]
Yeah that worked thanks!
